### ISSUE TITLE
Why byte[]?

### ISSUE THREAD

**Issue by fulldecent** [jennijuju/Aion-ATS-Token-Contract-Java#3]
The interface uses byte[] for numbers. Since this interface is in the Java world, not the consensus blockchain level, then why is byte[] used instead of a more canonical integer or BigInteger?

**Comment by jennijuju** [comment]
To support the most precise decimals, we are using the [smallest unit](https://github.com/aionnetwork/aion/wiki/Aion-Terminology) for the token, which is 18 decimals.  Using type as `integer` or `long` will easily overfloat the max value of these two types.

As for `BigInteger`, it is not a supported AVM ABI type, regarding the[AVM ABI spec](https://github.com/aionnetwork/AVM/wiki/ABI-Specification#data-types).

**Comment by fulldecent** [comment]
I believe a 128-bit unsigned integer will be used many times in Aion. It may make sense to promote that to a support type in AVM.

But at a minimum, there could be some documentation about `byte[]`. How is it encoded (big endian?) How should I do math on it?

**Comment by jennijuju** [comment]
Soon to come - BI for ABI
